<Project Sdk="Microsoft.NET.Sdk">

  <Import Project=".\Custom.Exporter._Common.Build.props" />

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <Import Project=".\Custom.Exporter._References.Build.props" />

  <Import Project=".\Custom.Exporter._Targets.Build.targets" />

</Project>